Registry: abscodes::registry::RegistryKey Class Reference
abscodes::registry::RegistryKey Class Reference
Public Types
enum ExpandStringOption { DontExpand, Expand }
Public Member Functions
RegistryKey ()=default
Initialize an empty RegistryKey.
RegistryKey (RegistryHive hive) noexcept
Initialize a empty RegistryKey.
RegistryKey (RegistryHive hive, RegistryView view) noexcept
Initialize a empty RegistryKey.
RegistryKey (RegistryHive hive, RegistryView view, RegistryAccessRights desiredAccess) noexcept
Initialize a empty RegistryKey.
RegistryKey (RegistryKey &&other) noexcept
Take ownership of the input key handle.
RegistryKey & operator= (RegistryKey &&other) noexcept
Move-assign from the input key handle.
RegistryKey (const RegistryKey &)=delete
Non copyable.
RegistryKey & operator= (const RegistryKey &)=delete
Non copyable.
bool IsValid () const noexcept
Is the wrapped HKEY handle valid?
operator bool () const noexcept
Same as IsValid(), but allow a short "if (regKey)" syntax.
RegistryHive GetHive () const
RegistryView GetView () const
RegistryAccessRights GetAccessRights () const
std::string GetName () const
size_t GetSubKeyCount ()
size_t GetValueCount ()
HKEY Get () const noexcept
Access the wrapped handle.
void Close () noexcept
Closes this key, flushes it to disk if the contents have been modified.
void Flush ()
Flush the content to disk.
void Dispose () noexcept
HKEY Detach () noexcept
Transfer ownership of current HKEY to the caller.
void Attach (RegistryHive hive) noexcept
Take ownership of the input HKEY handle.
void SwapWith (RegistryKey &other) noexcept
Non-throwing swap; Note: There's also a non-member swap overload.
RegistryKey CreateSubKey (std::string subkey)
Creates a new subkey, or opens an existing one.
RegistryKey CreateSubKey (std::string subkey, RegistryAccessRights desiredAccess)
Creates a new subkey, or opens an existing one.
RegistryKey CreateSubKey (std::string subkey, RegistryView view, RegistryAccessRights desiredAccess, RegistryOption option)
Creates a new subkey, or opens an existing one.
RegistryKey OpenSubKey (std::string subkey)
Open a subkey.
RegistryKey OpenSubKey (std::string subkey, RegistryAccessRights desiredAccess)
Open a subkey.
RegistryKey OpenSubKey (std::string subkey, RegistryView view, RegistryAccessRights desiredAccess, RegistryOption option)
Open a subkey.
void DeleteSubKey (std::string subkey, RegistryAccessRights desiredAccess=RegistryAccessRights::AllAccess)
Deletes the specified subkey.
void DeleteSubKey (std::string subkey, RegistryView view, RegistryAccessRights desiredAccess=RegistryAccessRights::AllAccess)
Deletes the specified subkey.
void DeleteSubKeyTree (std::string subkey, RegistryAccessRights desiredAccess=RegistryAccessRights::AllAccess)
Deletes the specified subkey and its tree.
void DeleteSubKeyTree (std::string subkey, RegistryView view, RegistryAccessRights desiredAccess=RegistryAccessRights::AllAccess)
Deletes the specified subkey and its tree.
void DeleteValue (std::string valueName)
Deletes the specified value from this key.
void SetValue (const std::string &valueName, const RegistryValue &value)
void SetDwordValue (const std::string &valueName, DWORD value)
void SetQwordValue (const std::string &valueName, const ULONGLONG &value)
void SetStringValue (const std::string &valueName, const std::string &value)
void SetExpandStringValue (const std::string &valueName, const std::string &value)
void SetMultiStringValue (const std::string &valueName, const std::vector< std::string > &value)
void SetBinaryValue (const std::string &valueName, const std::vector< BYTE > &value)
void SetBinaryValue (const std::string &valueName, const BYTE lpByte[], DWORD &dataSize)
RegistryValue GetValue (const std::string &valueName)
DWORD GetDwordValue (const std::string &valueName)
ULONGLONG GetQwordValue (const std::string &valueName)
std::string GetStringValue (const std::string &valueName)
std::string GetExpandStringValue (const std::string &valueName, ExpandStringOption expandOption=ExpandStringOption::DontExpand)
std::vector< std::string > GetMultiStringValue (const std::string &valueName)
std::vector< BYTE > GetBinaryValue (const std::string &valueName)
DWORD QueryValueType (const std::string &valueName)
Return the DWORD type ID for the input registry value.
void QueryInfoKey (DWORD &subKeys, DWORD &values, FILETIME &lastWriteTime)
std::vector< std::string > EnumSubKeys ()
Enumerate the subkeys of the registry key, using RegEnumKeyEx.
std::vector< std::pair< std::string, RegistryValueType > > EnumValues ()
Enumerate the values under the registry key, using RegEnumValue.
void EnableReflectionKey ()
void DisableReflectionKey ()
bool QueryReflectionKey ()
Private Member Functions
RegistryKey (const RegistryKey &, HKEY hKey, std::string subkey)
Internal copy constructor.
void Dispose (bool disposing)
Close the key.
bool IsSystemKey () const
Check if the current key is a system key.
bool IsPerfDataKey () const
Check if the current key is HKEY_PERFORMANCE_DATA.
bool IsWritable () const
bool IsDirty () const
void setDirty ()
void EnsureNotDisposed () const
Ensure the key is not closed.
void EnsureWriteable () const
Ensure the key is writable.
void ValidateKeyName (std::string &keyName)
std::string & FixupName (std::string &name)
Fixup multiple slashes to a single slash.
Private Attributes
RegistryHive _hive
RegistryView _view = RegistryView::Default
RegistryAccessRights _access = RegistryAccessRights::Read
HKEY _hKey = nullptr
The wrapped registry key handle.
std::string _keyName
Key name.
bool _dirty = false
Tells if the needs to be flush.
const size_t _maxKeyLength = 255
MSDN defines the following limits for registry key names & values: Key Name: 255 characters Value name: 16,383 Unicode characters Value: either 1 MB or current available memory, depending on registry format.
const size_t _maxValueLength = 16383
Constructor & Destructor Documentation
RegistryKey()
abscodes::registry::RegistryKey::RegistryKey (RegistryKey && other) noexcept
Take ownership of the input key handle.
The input key handle wrapper is reset to an empty state.
Member Function Documentation
Attach()
void abscodes::registry::RegistryKey::Attach (RegistryHive hive) noexcept
Take ownership of the input HKEY handle.
Safely close any previously open handle. Input key handle can be nullptr.
CreateSubKey() [1/3]
RegistryKey abscodes::registry::RegistryKey::CreateSubKey (std::string subkey)
Creates a new subkey, or opens an existing one.
Parameters
subkey Name or path to subkey to create or open.
desiredAccess Access rights, default to all access.
Exceptions
todo.
Referenced by CreateSubKey().
CreateSubKey() [2/3]
RegistryKey abscodes::registry::RegistryKey::CreateSubKey (std::string subkey, RegistryAccessRights desiredAccess)
Creates a new subkey, or opens an existing one.
Parameters
subkey Name or path to subkey to create or open.
desiredAccess Access rights, default to all access.
Exceptions
todo.
References CreateSubKey().
CreateSubKey() [3/3]
RegistryKey abscodes::registry::RegistryKey::CreateSubKey (std::string subkey, RegistryView view, RegistryAccessRights desiredAccess, RegistryOption option)
Creates a new subkey, or opens an existing one.
Parameters
subkey Name or path to subkey to create or open.
view todo
desiredAccess Access rights, default to all access.
option todo
Exceptions
todo.
References _hKey, _keyName, EnsureWriteable(), IsValid(), and RegistryKey().
DeleteSubKey() [1/2]
void abscodes::registry::RegistryKey::DeleteSubKey (std::string subkey, RegistryAccessRights desiredAccess = RegistryAccessRights::AllAccess)
Deletes the specified subkey.
Will throw an exception if the subkey has subkeys. To delete a tree of subkeys use, DeleteSubKeyTree.
Parameters
subkey SubKey to delete.
desiredAccess Access rights, default to all access.
Exceptions
RegistryException thrown if the subkey has child subkeys.
DeleteSubKey() [2/2]
void abscodes::registry::RegistryKey::DeleteSubKey (std::string subkey, RegistryView view, RegistryAccessRights desiredAccess = RegistryAccessRights::AllAccess)
Deletes the specified subkey.
Will throw an exception if the subkey has subkeys. To delete a tree of subkeys use, DeleteSubKeyTree.
Parameters
subkey SubKey to delete.
desiredAccess Access rights, default to all access.
Exceptions
RegistryException thrown if the subkey has child subkeys.
References _hKey, EnsureWriteable(), and IsValid().
DeleteSubKeyTree() [1/2]
void abscodes::registry::RegistryKey::DeleteSubKeyTree (std::string subkey, RegistryAccessRights desiredAccess = RegistryAccessRights::AllAccess)
Deletes the specified subkey and its tree.
Parameters
subkey SubKey to delete.
Exceptions
todo.
DeleteSubKeyTree() [2/2]
void abscodes::registry::RegistryKey::DeleteSubKeyTree (std::string subkey, RegistryView view, RegistryAccessRights desiredAccess = RegistryAccessRights::AllAccess)
Deletes the specified subkey and its tree.
Parameters
desiredAccess Access rights, default to all access.
subkey SubKey to delete.
References EnsureWriteable(), IsValid(), and OpenSubKey().
DeleteValue()
void abscodes::registry::RegistryKey::DeleteValue (std::string valueName)
Deletes the specified value from this key.
Parameters
name Name of value to delete.
References _hKey, and IsValid().
Detach()
HKEY abscodes::registry::RegistryKey::Detach () noexcept
Transfer ownership of current HKEY to the caller.
Note that the caller is responsible for closing the key handle!
References _hKey.
EnumValues()
std::vector< std::pair< std::string, RegistryValueType > > abscodes::registry::RegistryKey::EnumValues ()
Enumerate the values under the registry key, using RegEnumValue.
Returns a vector of pairs: In each pair, the wstring is the value name, the DWORD is the value type.
References _hKey, and IsValid().
OpenSubKey() [1/3]
RegistryKey abscodes::registry::RegistryKey::OpenSubKey (std::string subkey)
Open a subkey.
Will throw an exception if the subkey doesn't exist
Parameters
subkey Name or path to subkey to create or open.
Exceptions
todo.
Referenced by DeleteSubKeyTree(), and OpenSubKey().
OpenSubKey() [2/3]
RegistryKey abscodes::registry::RegistryKey::OpenSubKey (std::string subkey, RegistryAccessRights desiredAccess)
Open a subkey.
Will throw an exception if the subkey doesn't exist
Parameters
subkey Name or path to subkey to create or open.
desiredAccess Access rights, default to all access.
Exceptions
todo.
References OpenSubKey().
OpenSubKey() [3/3]
RegistryKey abscodes::registry::RegistryKey::OpenSubKey (std::string subkey, RegistryView view, RegistryAccessRights desiredAccess, RegistryOption option)
Open a subkey.
Will throw an exception if the subkey doesn't exist
Parameters
subkey Name or path to subkey to create or open.
view todo
desiredAccess Access rights, default to all access.
option todo
Exceptions
todo.
References _hKey, _keyName, IsValid(), and RegistryKey().
operator=()
RegistryKey & abscodes::registry::RegistryKey::operator= (RegistryKey && other) noexcept
Move-assign from the input key handle.
Properly check against self-move-assign (which is safe and does nothing).
Member Data Documentation
_maxKeyLength
const size_t abscodes::registry::RegistryKey::_maxKeyLength = 255 private
MSDN defines the following limits for registry key names & values: Key Name: 255 characters Value name: 16,383 Unicode characters Value: either 1 MB or current available memory, depending on registry format.
The documentation for this class was generated from the following files:
include/registry/RegistryKey.h
src/registry/RegistryKey.cpp